// Theme configuration based on the Capsule design screenshots:
// warm cream surfaces, brown text, vivid orange accent.
export const theme = {
  colors: {
    light: {
      title: '#46261C',
      background: '#F4EDE0',
      backgroundSecondary: '#E9E0CC',
      primary: '#EA6A2B',
      secondary: '#C9531B',
      text: '#6F6354',
      textSecondary: '#A2937F',
      border: '#DCCFB6',
      overlay: 'rgba(0, 0, 0, 0.5)',
      overlayLight: 'rgba(70, 38, 28, 0.08)',
      success: '#35C759',
      warning: '#FF8C00',
      error: '#D93025',
      cardBackground: '#EFE7D6',
      cardText: '#46261C',
      activeGreen: '#35C759',
      inactiveGray: '#A2937F',
      bubbleOwn: '#EA6A2B',
      bubbleOwnText: '#5A2208',
      bubbleOther: '#E9E0CC',
    },
    dark: {
      title: '#F3E9DB',
      background: '#221C15',
      backgroundSecondary: '#322A20',
      primary: '#EA6A2B',
      secondary: '#FF8A50',
      text: '#D8CCBA',
      textSecondary: '#9B8D79',
      border: '#453A2C',
      overlay: 'rgba(0, 0, 0, 0.6)',
      overlayLight: 'rgba(255, 255, 255, 0.06)',
      success: '#35C759',
      warning: '#FF8C00',
      error: '#FF5C4D',
      cardBackground: '#2C251B',
      cardText: '#F3E9DB',
      activeGreen: '#35C759',
      inactiveGray: '#7C7060',
      bubbleOwn: '#EA6A2B',
      bubbleOwnText: '#3A1503',
      bubbleOther: '#322A20',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    xxxl: 64,
    component: 16,
    section: 24,
    page: 20,
    statusBar: 44,
    safeArea: 34,
  },
  typography: {
    sizes: {
      h1: 28,
      h2: 24,
      h3: 20,
      body: 16,
      bodySmall: 14,
      caption: 12,
      appTitle: 22,
    },
    weights: {
      light: '300' as const,
      regular: '400' as const,
      medium: '500' as const,
      semibold: '600' as const,
      bold: '700' as const,
    },
    lineHeights: {
      tight: 1.2,
      normal: 1.4,
      relaxed: 1.6,
    },
  },
  borderRadius: {
    none: 0,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    full: 9999,
    avatar: 9999,
    card: 16,
    button: 12,
    moment: 20,
  },
  shadows: {
    none: 'none',
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
  },
} as const;

export type Theme = typeof theme;
export type ThemeColors = typeof theme.colors.light | typeof theme.colors.dark;
export type ColorScheme = 'light' | 'dark';
