// Theme configuration based on Capsules design system
export const theme = {
  colors: {
    light: {
      title: '#0F0F0F',
      background: '#f8f5f0',
      backgroundSecondary: '#ffffff',
      primary: '#44ff00',
      secondary: '#FF1200',
      text: '#5b645b',
      textSecondary: '#8a8a8a',
      border: '#e5e5e5',
      overlay: 'rgba(0, 0, 0, 0.7)',
      overlayLight: 'rgba(0, 0, 0, 0.1)',
      success: '#44ff00',
      warning: '#FF8C00',
      error: '#FF1200',
      cardBackground: '#3a3a3a',
      cardText: '#ffffff',
      activeGreen: '#44ff00',
      inactiveGray: '#8a8a8a',
    },
    dark: {
      title: '#ffffff',
      background: '#1a1a1a',
      backgroundSecondary: '#2a2a2a',
      primary: '#44ff00',
      secondary: '#FF1200',
      text: '#e0e0e0',
      textSecondary: '#a0a0a0',
      border: '#404040',
      overlay: 'rgba(255, 255, 255, 0.1)',
      overlayLight: 'rgba(255, 255, 255, 0.05)',
      success: '#44ff00',
      warning: '#FF8C00',
      error: '#FF1200',
      cardBackground: '#2a2a2a',
      cardText: '#ffffff',
      activeGreen: '#44ff00',
      inactiveGray: '#6a6a6a',
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
    xxxl: 64,
    component: 16,
    section: 24,
    page: 20,
    statusBar: 44,
    safeArea: 34,
  },
  typography: {
    sizes: {
      h1: 28,
      h2: 24,
      h3: 20,
      body: 16,
      bodySmall: 14,
      caption: 12,
      appTitle: 22,
    },
    weights: {
      light: '300' as const,
      regular: '400' as const,
      medium: '500' as const,
      semibold: '600' as const,
      bold: '700' as const,
    },
    lineHeights: {
      tight: 1.2,
      normal: 1.4,
      relaxed: 1.6,
    },
  },
  borderRadius: {
    none: 0,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 20,
    xxl: 24,
    full: 9999,
    avatar: 9999,
    card: 16,
    button: 12,
    moment: 20,
  },
  shadows: {
    none: 'none',
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 1,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
      elevation: 5,
    },
  },
} as const;

export type Theme = typeof theme;
export type ThemeColors = typeof theme.colors.light | typeof theme.colors.dark;
export type ColorScheme = 'light' | 'dark';